---
- hosts: all
  vars:
    setuppy_install_dir: /home/pi/hodor_picontroller
    controller_install_dir: /home/pi/hodor_picontroller
    controller_log_dir: /home/pi/log
    controller_run_dir: /home/pi
    slackbot_install_dir: /home/pi/hodor_picontroller
    slackbot_log_dir: /home/pi/log
    slackbot_run_dir: /home/pi
    runhodor_install_dir: /home/pi
  remote_user: pi
  tasks:
      - name: install yaml using apt-get
        apt:
          name: python-yaml
          state: present
        become: yes
        become_user: root
      - name: install python-serial using apt-get
        apt:
          name: python-serial
          state: present
        become: yes
        become_user: root
      - name: download get-pip.py
        get_url:
          url: https://bootstrap.pypa.io/get-pip.py
          dest: /tmp/get-pip.py
          checksum: sha256:19dae841a150c86e2a09d475b5eb0602861f2a5b7761ec268049a662dbd2bd0c
      - name: install pip using get-pip.py
        command: python /tmp/get-pip.py
        args:
          creates: /usr/local/bin/pip
        become: yes
        become_user: root
      - name: install setuptools with pip
        command: pip install setuptools
        args:
          creates: /usr/local/lib/python2.7/dist-packages/setuptools/__init__.py
        become: yes
        become_user: root
      - name: install wiringpi with pip
        command: pip install wiringpi
        args:
          creates: /usr/local/lib/python2.7/dist-packages/wiringpi.py
        become: yes
        become_user: root
      - name: drop hodor_controller package files
        synchronize:
          src: ../hodor_controller
          dest: "{{ controller_install_dir }}"
          rsync_opts: "--exclude=*.pyc"
      - name: drop hodor_slackbot package files
        synchronize:
          src: ../hodor_slackbot
          dest: "{{ slackbot_install_dir }}"
          rsync_opts: "--exclude=*.pyc"
      - name: drop setup.py install script
        copy:
          src: ../setup.py
          dest: "{{ setuppy_install_dir }}"
      - name: drop example card key file if no card key file
        copy:
          src: files/example_bw_cardkey.csv
          dest: /home/pi
          force: no
      - name: create controller log dir if needed
        file:
          path: "{{ controller_log_dir }}"
          state: directory
          mode: 0755
      - name: create slackbot log dir if needed
        file:
          path: "{{ slackbot_log_dir }}"
          state: directory
          mode: 0755
      - name: install hodor_watcher and hodor_slacker
        command: python setup.py develop
        args:
          creates: /usr/local/bin/hodor_slacker
          chdir: "{{ setuppy_install_dir }}"
        become: yes
        become_user: root
      - name: drop run_hodor_watcher.sh script
        template:
          src: scripts/run_hodor_watcher.sh
          dest: "{{ runhodor_install_dir }}"
          mode: 0755
      - name: drop run_hodor_slacker.sh script
        template:
          src: scripts/run_hodor_slacker.sh
          dest: "{{ runhodor_install_dir }}"
          mode: 0755
      - name: install hodor_watcher init.d script
        copy:
          src: scripts/etc_init.d_hodor_watcher
          dest: /etc/init.d/hodor_watcher
          mode: 0755
        become: yes
        become_user: root
      - name: install hodor_slacker init.d script
        copy:
          src: scripts/etc_init.d_hodor_slacker
          dest: /etc/init.d/hodor_slacker
          mode: 0755
        become: yes
        become_user: root
      - name: update init.d links for hodor_watcher
        command: update-rc.d hodor_watcher defaults
        args:
          creates: /etc/rc?.d/*hodor_watcher
        become: yes
        become_user: root
      - name: install hodor_slacker init.d script
        copy:
          src: scripts/etc_init.d_hodor_slacker
          dest: /etc/init.d/hodor_slacker
          mode: 0755
        become: yes
        become_user: root
      - name: update init.d links for hodor_slacker
        command: update-rc.d hodor_slacker defaults
        args:
          creates: /etc/rc?.d/*hodor_slacker
        become: yes
        become_user: root
      - name: update init.d links with systemd
        command: systemctl daemon-reload
        become: yes
        become_user: root
      - name: restart hodor_watcher service
        command: /etc/init.d/hodor_watcher restart
        become: yes
        become_user: root
      - name: restart hodor_slacker service
        command: /etc/init.d/hodor_slacker restart
        become: yes
        become_user: root
